language: csharp
solution: MetacoItBit.sln

install:
  - nuget restore MetacoItBit.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MetacoItBit.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MetacoItBitClient.Tests/bin/Release/MetacoItBit.Tests.dll

